export {
  applyStash,
  checkoutRef,
  commitChanges,
  createStash,
  discardFiles,
  dropStash,
  fetchAll,
  initializeGit,
  isGitAvailable,
  listBranches,
  listStashes,
  popStash,
  pullCurrentBranch,
  readCommit,
  readGitStatus,
  readLog,
  readWorkingDiff,
  stageFiles,
  unstageFiles,
  watchGitProjects,
  type GitProjectWatcher
} from "./service";
